function atk(partial) {
  return {
    startup: 6,
    active: 4,
    recovery: 12,
    damage: 6,
    kbBase: 8,
    kbScale: 0.42,
    angle: 45,
    hitstun: 14,
    hitlag: 6,
    shieldDamage: 4,
    sprite: "punch",
    hitbox: { x: 18, y: -62, w: 42, h: 30 },
    cancel: null,
    projectile: null,
    vx: 0,
    vy: 0,
    invuln: 0,
    name: "atk",
    ...partial,
  };
}

export const CHARACTERS = {
  fernanda: {
    id: "fernanda",
    name: "Fernanda",
    archetype: "Técnica",
    color: "#ff74b1",
    portrait: "ui/portrait_fernanda.png",
    scale: 0.32,
    hurtW: 40,
    hurtH: 78,
    weight: 86,
    speed: 5.4,
    runSpeed: 7.6,
    accel: 0.7,
    friction: 0.72,
    airAccel: 0.38,
    airSpeed: 5.2,
    jump: 13.6,
    airJump: 12.4,
    gravity: 0.52,
    maxFall: 11,
    fastFall: 14.5,
    jumps: 2,
    anim: {
      idle: ["fernanda/idle_0.png", "fernanda/idle_1.png"],
      walk: ["fernanda/walk_0.png", "fernanda/walk_1.png"],
      run: ["fernanda/run.png"],
      jump: ["fernanda/jump.png"],
      punch: ["fernanda/punch.png"],
      special: ["fernanda/special.png"],
      crouch: ["fernanda/crouch.png"],
      hurt: ["fernanda/hurt.png"],
      win: ["fernanda/win.png"],
      down: ["fernanda/down.png"],
    },
    moves: {
      jab: atk({
        name: "Soco",
        startup: 4,
        active: 3,
        recovery: 9,
        damage: 3.5,
        kbBase: 4,
        kbScale: 0.18,
        angle: 55,
        hitstun: 12,
        cancel: "jab2",
      }),
      jab2: atk({
        name: "Gatilho",
        startup: 5,
        active: 4,
        recovery: 14,
        damage: 4.5,
        kbBase: 7,
        kbScale: 0.28,
        angle: 48,
        hitstun: 13,
      }),
      strong: atk({
        name: "Cruzado",
        startup: 11,
        active: 5,
        recovery: 18,
        damage: 13,
        kbBase: 14,
        kbScale: 0.72,
        angle: 38,
        hitstun: 22,
        hitlag: 10,
        sprite: "punch",
        hitbox: { x: 22, y: -66, w: 50, h: 34 },
      }),
      nair: atk({
        name: "Aéreo",
        startup: 7,
        active: 8,
        recovery: 12,
        damage: 8,
        kbBase: 8,
        kbScale: 0.4,
        angle: 42,
        sprite: "jump",
        hitbox: { x: 8, y: -70, w: 46, h: 50 },
      }),
      dair: atk({
        name: "Aéreo baixo",
        startup: 10,
        active: 6,
        recovery: 16,
        damage: 9,
        kbBase: 6,
        kbScale: 0.5,
        angle: 270,
        sprite: "jump",
        hitbox: { x: -10, y: -28, w: 36, h: 36 },
      }),
      uair: atk({
        name: "Aéreo alto",
        startup: 7,
        active: 5,
        recovery: 14,
        damage: 8,
        kbBase: 9,
        kbScale: 0.45,
        angle: 82,
        sprite: "jump",
        hitbox: { x: -8, y: -96, w: 40, h: 36 },
      }),
      nspecial: atk({
        name: "Coração",
        startup: 12,
        active: 2,
        recovery: 22,
        damage: 0,
        sprite: "special",
        projectile: {
          kind: "heart",
          sprite: "fx/heart.png",
          speed: 9.5,
          life: 70,
          w: 36,
          h: 28,
          damage: 8,
          kbBase: 9,
          kbScale: 0.4,
          angle: 35,
          scale: 0.22,
        },
      }),
      sspecial: atk({
        name: "Didi",
        startup: 10,
        active: 3,
        recovery: 26,
        damage: 0,
        sprite: "run",
        projectile: {
          kind: "didi",
          sprite: "cats/didi_fire.png",
          speed: 11,
          life: 42,
          w: 48,
          h: 32,
          damage: 11,
          kbBase: 12,
          kbScale: 0.55,
          angle: 32,
          scale: 0.38,
        },
      }),
      uspecial: atk({
        name: "Tom — recuperação",
        startup: 6,
        active: 10,
        recovery: 18,
        damage: 7,
        kbBase: 8,
        kbScale: 0.38,
        angle: 88,
        sprite: "jump",
        vy: -15.5,
        vx: 2.2,
        invuln: 8,
        hitbox: { x: -16, y: -90, w: 48, h: 70 },
      }),
      dspecial: atk({
        name: "Tom — orbe",
        startup: 14,
        active: 2,
        recovery: 24,
        damage: 0,
        sprite: "crouch",
        projectile: {
          kind: "orb",
          sprite: "cats/tom_orb.png",
          speed: 7.2,
          life: 80,
          w: 34,
          h: 34,
          damage: 10,
          kbBase: 10,
          kbScale: 0.6,
          angle: 50,
          scale: 0.34,
        },
      }),
      throw: atk({
        name: "Arremesso",
        startup: 8,
        active: 2,
        recovery: 16,
        damage: 7,
        kbBase: 10,
        kbScale: 0.5,
        angle: 40,
      }),
    },
  },

  nox: {
    id: "nox",
    name: "Nox",
    archetype: "Pesado",
    color: "#ff6a3d",
    portrait: "ui/portrait_nox.png",
    scale: 0.38,
    hurtW: 48,
    hurtH: 84,
    weight: 118,
    speed: 3.8,
    runSpeed: 5.6,
    accel: 0.5,
    friction: 0.78,
    airAccel: 0.28,
    airSpeed: 4.1,
    jump: 12.4,
    airJump: 11.2,
    gravity: 0.62,
    maxFall: 13,
    fastFall: 16,
    jumps: 2,
    anim: {
      idle: ["nox/idle_0.png", "nox/idle_1.png"],
      walk: ["nox/walk.png"],
      run: ["nox/run.png"],
      jump: ["nox/jump.png"],
      punch: ["nox/punch.png"],
      special: ["nox/punch.png"],
      crouch: ["nox/charge.png"],
      hurt: ["nox/hurt.png"],
      win: ["nox/idle_1.png"],
      down: ["nox/hurt.png"],
      charge: ["nox/charge.png"],
    },
    moves: {
      jab: atk({
        name: "Jab",
        startup: 5,
        active: 4,
        recovery: 11,
        damage: 5,
        kbBase: 6,
        kbScale: 0.22,
        angle: 50,
        cancel: "jab2",
        hitbox: { x: 20, y: -64, w: 46, h: 32 },
      }),
      jab2: atk({
        name: "Gancho",
        startup: 7,
        active: 5,
        recovery: 16,
        damage: 7,
        kbBase: 9,
        kbScale: 0.34,
        angle: 46,
        hitbox: { x: 22, y: -70, w: 48, h: 36 },
      }),
      strong: atk({
        name: "Martelo",
        startup: 14,
        active: 6,
        recovery: 22,
        damage: 17,
        kbBase: 18,
        kbScale: 0.88,
        angle: 36,
        hitlag: 12,
        sprite: "punch",
        hitbox: { x: 24, y: -68, w: 58, h: 38 },
      }),
      nair: atk({
        name: "Aéreo",
        startup: 8,
        active: 7,
        recovery: 14,
        damage: 10,
        kbBase: 10,
        kbScale: 0.48,
        angle: 40,
        sprite: "jump",
        hitbox: { x: 6, y: -72, w: 50, h: 54 },
      }),
      dair: atk({
        name: "Meteor",
        startup: 12,
        active: 6,
        recovery: 18,
        damage: 12,
        kbBase: 8,
        kbScale: 0.55,
        angle: 270,
        sprite: "charge",
        hitbox: { x: -12, y: -30, w: 40, h: 40 },
      }),
      uair: atk({
        name: "Upper aéreo",
        startup: 8,
        active: 5,
        recovery: 16,
        damage: 11,
        kbBase: 11,
        kbScale: 0.5,
        angle: 80,
        sprite: "jump",
        hitbox: { x: -10, y: -100, w: 44, h: 40 },
      }),
      nspecial: atk({
        name: "Onda de choque",
        startup: 16,
        active: 4,
        recovery: 28,
        damage: 12,
        kbBase: 12,
        kbScale: 0.6,
        angle: 30,
        sprite: "punch",
        hitbox: { x: 20, y: -58, w: 86, h: 34 },
      }),
      sspecial: atk({
        name: "Investida",
        startup: 8,
        active: 14,
        recovery: 18,
        damage: 14,
        kbBase: 13,
        kbScale: 0.62,
        angle: 28,
        sprite: "charge",
        vx: 11,
        hitbox: { x: 10, y: -60, w: 56, h: 44 },
      }),
      uspecial: atk({
        name: "Uppercut",
        startup: 7,
        active: 12,
        recovery: 20,
        damage: 13,
        kbBase: 10,
        kbScale: 0.5,
        angle: 85,
        sprite: "jump",
        vy: -16.2,
        vx: 1.4,
        invuln: 6,
        hitbox: { x: -8, y: -96, w: 46, h: 80 },
      }),
      dspecial: atk({
        name: "Pisão",
        startup: 12,
        active: 6,
        recovery: 24,
        damage: 15,
        kbBase: 14,
        kbScale: 0.7,
        angle: 70,
        sprite: "charge",
        hitbox: { x: -28, y: -36, w: 72, h: 36 },
      }),
      throw: atk({
        name: "Arremesso",
        startup: 10,
        active: 2,
        recovery: 18,
        damage: 9,
        kbBase: 12,
        kbScale: 0.55,
        angle: 38,
      }),
    },
  },
};

export const CHARACTER_IDS = Object.keys(CHARACTERS);
