function atk(partial) {
  return {
    startup: 6,
    active: 4,
    recovery: 12,
    damage: 6,
    kbBase: 8,
    kbScale: 0.42,
    angle: 45,
    hitstun: 14,
    hitlag: 6,
    shieldDamage: 4,
    sprite: "punch",
    hitbox: { x: 18, y: -62, w: 42, h: 30 },
    cancel: null,
    projectile: null,
    assist: null,
    superMove: false,
    isLasso: false,
    vx: 0,
    vy: 0,
    invuln: 0,
    name: "atk",
    ...partial,
  };
}

export const CHARACTERS = {
  evertinho: {
    id: "evertinho",
    name: "Everttinho",
    title: "O Peão Lendário",
    archetype: "Peão / Laçador",
    color: "#e8b84a",
    portrait: "ui/portrait_evertinho.jpg",
    scale: 0.34,
    hurtW: 46,
    hurtH: 82,
    weight: 104,
    speed: 4.8,
    runSpeed: 7.2,
    accel: 0.62,
    friction: 0.76,
    airAccel: 0.34,
    airSpeed: 4.8,
    jump: 13.2,
    airJump: 12.0,
    gravity: 0.58,
    maxFall: 12.2,
    fastFall: 15.2,
    jumps: 2,
    anim: {
      idle: ["evertinho/idle_0.png", "evertinho/idle_1.png"],
      walk: ["evertinho/walk_0.png", "evertinho/walk_1.png"],
      run: ["evertinho/run.png"],
      jump: ["evertinho/jump.png"],
      punch: ["evertinho/punch.png"],
      special: ["evertinho/spin.png"],
      crouch: ["evertinho/throw.png"],
      hurt: ["evertinho/hurt.png"],
      win: ["evertinho/point.png"],
      down: ["evertinho/hurt.png"],
      charge: ["evertinho/mount.png"],
      throw: ["evertinho/throw.png"],
      point: ["evertinho/point.png"],
    },
    moves: {
      jab: atk({
        name: "Laço Chicote",
        startup: 5,
        active: 8,
        recovery: 10,
        damage: 5,
        kbBase: 5,
        kbScale: 0.22,
        angle: 65,
        hitstun: 13,
        cancel: "jab2",
        isLasso: true,
        sprite: "special",
        hitbox: { x: -10, y: -78, w: 84, h: 78 },
      }),
      jab2: atk({
        name: "Laço Puxão",
        startup: 6,
        active: 5,
        recovery: 14,
        damage: 7,
        kbBase: 4,
        kbScale: 0.22,
        angle: 40,
        pull: true,
        isLasso: true,
        sprite: "throw",
        hitbox: { x: 18, y: -64, w: 76, h: 32 },
      }),
      strong: atk({
        name: "Tiro de Laço",
        startup: 11,
        active: 3,
        recovery: 20,
        damage: 0,
        sprite: "punch",
        isLasso: true,
        projectile: {
          kind: "lasso",
          sprite: "evertinho/lasso_loop.png",
          speed: 10.5,
          life: 44,
          w: 42,
          h: 28,
          damage: 12,
          kbBase: 10,
          kbScale: 0.5,
          angle: 32,
          scale: 0.24,
          pull: true,
          isLasso: true,
        },
      }),
      nair: atk({
        name: "Laço Giratório 360°",
        startup: 7,
        active: 8,
        recovery: 14,
        damage: 9.5,
        kbBase: 9,
        kbScale: 0.42,
        angle: 45,
        isLasso: true,
        sprite: "jump",
        hitbox: { x: 4, y: -72, w: 54, h: 56 },
      }),
      dair: atk({
        name: "Laço Descendente (Spike)",
        startup: 10,
        active: 6,
        recovery: 16,
        damage: 11,
        kbBase: 8,
        kbScale: 0.55,
        angle: 270,
        isLasso: true,
        sprite: "throw",
        hitbox: { x: -8, y: -28, w: 46, h: 38 },
      }),
      uair: atk({
        name: "Laço Celestial",
        startup: 7,
        active: 6,
        recovery: 14,
        damage: 9,
        kbBase: 10,
        kbScale: 0.45,
        angle: 84,
        isLasso: true,
        sprite: "jump",
        hitbox: { x: -10, y: -102, w: 50, h: 44 },
      }),
      nspecial: atk({
        name: "Laço Mágico da Aurora",
        startup: 12,
        active: 3,
        recovery: 22,
        damage: 0,
        sprite: "special",
        isLasso: true,
        projectile: {
          kind: "magic_lasso",
          sprite: "evertinho/lasso_magic.png",
          speed: 9.2,
          life: 65,
          w: 46,
          h: 36,
          damage: 13,
          kbBase: 11,
          kbScale: 0.55,
          angle: 30,
          scale: 0.22,
          isLasso: true,
          pull: true,
        },
      }),
      sspecial: atk({
        name: "Laço do Trovão",
        startup: 11,
        active: 3,
        recovery: 24,
        damage: 0,
        sprite: "throw",
        isLasso: true,
        projectile: {
          kind: "thunder_lasso",
          sprite: "evertinho/lasso_thunder.png",
          speed: 12.0,
          life: 52,
          w: 52,
          h: 32,
          damage: 14,
          kbBase: 12,
          kbScale: 0.65,
          angle: 38,
          scale: 0.24,
          isLasso: true,
        },
      }),
      uspecial: atk({
        name: "Salto do Peão",
        startup: 6,
        active: 12,
        recovery: 18,
        damage: 8,
        kbBase: 9,
        kbScale: 0.4,
        angle: 86,
        sprite: "mount",
        vy: -16.8,
        vx: 2.6,
        invuln: 9,
        hitbox: { x: -12, y: -96, w: 54, h: 86 },
      }),
      dspecial: atk({
        name: "Assistência do Cavalo 'Trovão'",
        startup: 12,
        active: 4,
        recovery: 26,
        damage: 0,
        sprite: "point",
        assist: {
          kind: "horse",
          sprite: "evertinho/horse_thunder.png",
          speed: 13.5,
          life: 75,
          w: 80,
          h: 60,
          damage: 15,
          kbBase: 13,
          kbScale: 0.65,
          angle: 42,
          scale: 0.32,
          sound: "horse_whinny",
        },
      }),
      throw: atk({
        name: "Arremesso de Laço",
        startup: 7,
        active: 3,
        recovery: 16,
        damage: 9,
        kbBase: 7,
        kbScale: 0.38,
        angle: 42,
        pull: true,
        isLasso: true,
        sprite: "throw",
        hitbox: { x: 16, y: -64, w: 88, h: 36 },
      }),
      super: atk({
        name: "Grande Rodeio da Aurora",
        startup: 16,
        active: 24,
        recovery: 32,
        damage: 32,
        kbBase: 19,
        kbScale: 0.95,
        angle: 45,
        hitstun: 50,
        superMove: true,
        invuln: 25,
        sprite: "mount",
        vx: 15,
        hitbox: { x: -20, y: -90, w: 120, h: 85 },
      }),
    },
  },

  fernanda: {
    id: "fernanda",
    name: "Fernanda",
    title: "A Feiticeira Felina",
    archetype: "Técnica / Mágica",
    color: "#ff74b1",
    portrait: "ui/portrait_fernanda.jpg",
    scale: 0.32,
    hurtW: 40,
    hurtH: 78,
    weight: 86,
    speed: 5.5,
    runSpeed: 7.8,
    accel: 0.72,
    friction: 0.72,
    airAccel: 0.4,
    airSpeed: 5.4,
    jump: 13.8,
    airJump: 12.6,
    gravity: 0.52,
    maxFall: 11,
    fastFall: 14.5,
    jumps: 2,
    anim: {
      idle: ["fernanda/idle_0.png", "fernanda/idle_1.png"],
      walk: ["fernanda/walk_0.png", "fernanda/walk_1.png"],
      run: ["fernanda/run.png"],
      jump: ["fernanda/jump.png"],
      punch: ["fernanda/punch.png"],
      special: ["fernanda/special.png"],
      crouch: ["fernanda/crouch.png"],
      hurt: ["fernanda/hurt.png"],
      win: ["fernanda/win.png"],
      down: ["fernanda/down.png"],
    },
    moves: {
      jab: atk({
        name: "Soco de Luz",
        startup: 4,
        active: 3,
        recovery: 9,
        damage: 4,
        kbBase: 4,
        kbScale: 0.18,
        angle: 55,
        hitstun: 12,
        cancel: "jab2",
      }),
      jab2: atk({
        name: "Chute Giratório",
        startup: 5,
        active: 4,
        recovery: 14,
        damage: 5,
        kbBase: 7,
        kbScale: 0.28,
        angle: 48,
        hitstun: 13,
      }),
      strong: atk({
        name: "Cruzado Neon",
        startup: 10,
        active: 5,
        recovery: 18,
        damage: 13,
        kbBase: 14,
        kbScale: 0.72,
        angle: 38,
        hitstun: 22,
        hitlag: 10,
        sprite: "punch",
        hitbox: { x: 22, y: -66, w: 50, h: 34 },
      }),
      nair: atk({
        name: "Giro Aéreo Felino",
        startup: 7,
        active: 8,
        recovery: 12,
        damage: 8.5,
        kbBase: 8,
        kbScale: 0.4,
        angle: 42,
        sprite: "jump",
        hitbox: { x: 8, y: -70, w: 46, h: 50 },
      }),
      dair: atk({
        name: "Meteoro de Salto",
        startup: 9,
        active: 6,
        recovery: 16,
        damage: 10,
        kbBase: 7,
        kbScale: 0.52,
        angle: 270,
        sprite: "jump",
        hitbox: { x: -10, y: -28, w: 38, h: 36 },
      }),
      uair: atk({
        name: "Chute Astral",
        startup: 6,
        active: 5,
        recovery: 14,
        damage: 8.5,
        kbBase: 9,
        kbScale: 0.45,
        angle: 82,
        sprite: "jump",
        hitbox: { x: -8, y: -96, w: 42, h: 38 },
      }),
      nspecial: atk({
        name: "Coração Mágico",
        startup: 11,
        active: 2,
        recovery: 20,
        damage: 0,
        sprite: "special",
        projectile: {
          kind: "heart",
          sprite: "fx/heart.png",
          speed: 9.8,
          life: 70,
          w: 36,
          h: 28,
          damage: 9,
          kbBase: 9,
          kbScale: 0.42,
          angle: 35,
          scale: 0.24,
        },
      }),
      sspecial: atk({
        name: "Assistência: Didi Fogo",
        startup: 10,
        active: 3,
        recovery: 24,
        damage: 0,
        sprite: "run",
        assist: {
          kind: "didi",
          sprite: "cats/didi_fire.png",
          speed: 11.5,
          life: 46,
          w: 48,
          h: 32,
          damage: 12,
          kbBase: 12,
          kbScale: 0.55,
          angle: 34,
          scale: 0.38,
        },
      }),
      uspecial: atk({
        name: "Tom — Voo Astral",
        startup: 5,
        active: 10,
        recovery: 18,
        damage: 8,
        kbBase: 8,
        kbScale: 0.38,
        angle: 88,
        sprite: "jump",
        vy: -15.8,
        vx: 2.3,
        invuln: 9,
        hitbox: { x: -16, y: -90, w: 48, h: 70 },
      }),
      dspecial: atk({
        name: "Armadilha de Tom",
        startup: 12,
        active: 2,
        recovery: 22,
        damage: 0,
        sprite: "crouch",
        projectile: {
          kind: "orb",
          sprite: "cats/tom_orb.png",
          speed: 7.5,
          life: 85,
          w: 36,
          h: 36,
          damage: 11,
          kbBase: 10,
          kbScale: 0.6,
          angle: 50,
          scale: 0.36,
        },
      }),
      throw: atk({
        name: "Arremesso Felino",
        startup: 7,
        active: 2,
        recovery: 15,
        damage: 8,
        kbBase: 10,
        kbScale: 0.5,
        angle: 40,
      }),
      super: atk({
        name: "Tempestade Felina Neon",
        startup: 15,
        active: 20,
        recovery: 30,
        damage: 30,
        kbBase: 18,
        kbScale: 0.9,
        angle: 48,
        hitstun: 48,
        superMove: true,
        invuln: 25,
        sprite: "special",
        hitbox: { x: -30, y: -95, w: 130, h: 90 },
      }),
    },
  },

  nox: {
    id: "nox",
    name: "Nox",
    title: "O Touro de Ferro",
    archetype: "Pesado / Brawler",
    color: "#6ef0ff",
    portrait: "ui/portrait_nox.jpg",
    scale: 0.33,
    hurtW: 48,
    hurtH: 84,
    weight: 122,
    speed: 4.0,
    runSpeed: 6.2,
    accel: 0.52,
    friction: 0.8,
    airAccel: 0.28,
    airSpeed: 4.2,
    jump: 12.2,
    airJump: 11.0,
    gravity: 0.64,
    maxFall: 13.0,
    fastFall: 16.0,
    jumps: 2,
    anim: {
      idle: ["nox/idle_0.png", "nox/idle_1.png"],
      walk: ["nox/walk.png"],
      run: ["nox/run.png"],
      jump: ["nox/jump.png"],
      punch: ["nox/punch.png"],
      special: ["nox/charge.png"],
      crouch: ["nox/charge.png"],
      hurt: ["nox/hurt.png"],
      win: ["nox/punch.png"],
      down: ["nox/hurt.png"],
    },
    moves: {
      jab: atk({
        name: "Marreta de Ferro",
        startup: 6,
        active: 4,
        recovery: 11,
        damage: 6.5,
        kbBase: 6,
        kbScale: 0.25,
        angle: 50,
        hitstun: 15,
        cancel: "jab2",
        sprite: "punch",
        hitbox: { x: 18, y: -64, w: 48, h: 32 },
      }),
      jab2: atk({
        name: "Gancho Titânico",
        startup: 7,
        active: 4,
        recovery: 15,
        damage: 8,
        kbBase: 9,
        kbScale: 0.35,
        angle: 60,
        hitstun: 16,
        sprite: "punch",
        hitbox: { x: 20, y: -72, w: 52, h: 36 },
      }),
      strong: atk({
        name: "Pancada Brutal",
        startup: 13,
        active: 6,
        recovery: 22,
        damage: 16,
        kbBase: 16,
        kbScale: 0.85,
        angle: 35,
        hitstun: 26,
        hitlag: 12,
        sprite: "charge",
        hitbox: { x: 24, y: -70, w: 60, h: 42 },
      }),
      nair: atk({
        name: "Pisão Aéreo",
        startup: 8,
        active: 8,
        recovery: 15,
        damage: 10,
        kbBase: 10,
        kbScale: 0.45,
        angle: 45,
        sprite: "jump",
        hitbox: { x: 6, y: -68, w: 50, h: 54 },
      }),
      dair: atk({
        name: "Impacto Sísmico",
        startup: 11,
        active: 7,
        recovery: 18,
        damage: 12,
        kbBase: 9,
        kbScale: 0.6,
        angle: 270,
        sprite: "charge",
        hitbox: { x: -10, y: -26, w: 46, h: 40 },
      }),
      uair: atk({
        name: "Cabeçada Titânica",
        startup: 8,
        active: 6,
        recovery: 15,
        damage: 10.5,
        kbBase: 11,
        kbScale: 0.5,
        angle: 85,
        sprite: "jump",
        hitbox: { x: -8, y: -98, w: 48, h: 42 },
      }),
      nspecial: atk({
        name: "Onda de Choque",
        startup: 13,
        active: 3,
        recovery: 24,
        damage: 0,
        sprite: "charge",
        projectile: {
          kind: "shockwave",
          sprite: "fx/burst.png",
          speed: 8.5,
          life: 60,
          w: 48,
          h: 36,
          damage: 12,
          kbBase: 11,
          kbScale: 0.55,
          angle: 42,
          scale: 0.28,
        },
      }),
      sspecial: atk({
        name: "Investida do Touro",
        startup: 12,
        active: 18,
        recovery: 20,
        damage: 15,
        kbBase: 15,
        kbScale: 0.7,
        angle: 32,
        sprite: "charge",
        vx: 13.0,
        invuln: 6,
        hitbox: { x: 10, y: -68, w: 76, h: 54 },
      }),
      uspecial: atk({
        name: "Uppercut Titânico",
        startup: 7,
        active: 10,
        recovery: 20,
        damage: 11,
        kbBase: 12,
        kbScale: 0.45,
        angle: 85,
        sprite: "punch",
        vy: -15.0,
        vx: 1.8,
        invuln: 8,
        hitbox: { x: -10, y: -92, w: 50, h: 78 },
      }),
      dspecial: atk({
        name: "Pisão Terremoto",
        startup: 14,
        active: 6,
        recovery: 26,
        damage: 13,
        kbBase: 13,
        kbScale: 0.65,
        angle: 75,
        sprite: "charge",
        hitbox: { x: -40, y: -30, w: 80, h: 35 },
      }),
      throw: atk({
        name: "Arremesso de Touro",
        startup: 9,
        active: 3,
        recovery: 18,
        damage: 9.5,
        kbBase: 11,
        kbScale: 0.52,
        angle: 45,
      }),
      super: atk({
        name: "Impacto de Barretos",
        startup: 18,
        active: 22,
        recovery: 32,
        damage: 34,
        kbBase: 20,
        kbScale: 1.0,
        angle: 45,
        hitstun: 50,
        superMove: true,
        invuln: 25,
        sprite: "punch",
        hitbox: { x: -40, y: -80, w: 140, h: 90 },
      }),
    },
  },

  touro_ferro: {
    id: "touro_ferro",
    name: "Touro de Ferro",
    title: "O Titã Blindado",
    archetype: "Chefe / Hiper Armadura",
    color: "#ff5252",
    portrait: "ui/portrait_nox.jpg",
    scale: 0.38,
    hurtW: 56,
    hurtH: 94,
    weight: 155,
    speed: 4.2,
    runSpeed: 6.8,
    accel: 0.6,
    friction: 0.82,
    airAccel: 0.3,
    airSpeed: 4.2,
    jump: 12.0,
    airJump: 10.5,
    gravity: 0.7,
    maxFall: 14.0,
    fastFall: 17.0,
    jumps: 2,
    anim: {
      idle: ["nox/idle_0.png", "nox/idle_1.png"],
      walk: ["nox/walk.png"],
      run: ["nox/run.png"],
      jump: ["nox/jump.png"],
      punch: ["nox/punch.png"],
      special: ["nox/charge.png"],
      crouch: ["nox/charge.png"],
      hurt: ["nox/hurt.png"],
      win: ["nox/punch.png"],
      down: ["nox/hurt.png"],
    },
    moves: {
      jab: atk({
        name: "Pancada de Aço",
        startup: 6,
        active: 5,
        recovery: 12,
        damage: 8,
        kbBase: 8,
        kbScale: 0.35,
        angle: 48,
        hitstun: 16,
        sprite: "punch",
        hitbox: { x: 20, y: -68, w: 56, h: 36 },
      }),
      strong: atk({
        name: "Arremetida Titânica",
        startup: 12,
        active: 6,
        recovery: 20,
        damage: 18,
        kbBase: 18,
        kbScale: 0.9,
        angle: 32,
        hitstun: 28,
        hitlag: 14,
        sprite: "charge",
        hitbox: { x: 26, y: -72, w: 70, h: 48 },
      }),
      nair: atk({
        name: "Pisão Pesado",
        startup: 8,
        active: 8,
        recovery: 14,
        damage: 12,
        kbBase: 11,
        kbScale: 0.5,
        angle: 45,
        sprite: "jump",
        hitbox: { x: 8, y: -70, w: 56, h: 56 },
      }),
      dair: atk({
        name: "Meteoro de Ferro",
        startup: 10,
        active: 7,
        recovery: 18,
        damage: 14,
        kbBase: 10,
        kbScale: 0.65,
        angle: 270,
        sprite: "charge",
        hitbox: { x: -10, y: -26, w: 52, h: 44 },
      }),
      uair: atk({
        name: "Chifre Titânico",
        startup: 8,
        active: 6,
        recovery: 15,
        damage: 12,
        kbBase: 12,
        kbScale: 0.55,
        angle: 85,
        sprite: "jump",
        hitbox: { x: -8, y: -102, w: 52, h: 44 },
      }),
      nspecial: atk({
        name: "Terremoto Sísmico",
        startup: 12,
        active: 3,
        recovery: 22,
        damage: 0,
        sprite: "charge",
        projectile: {
          kind: "shockwave",
          sprite: "fx/burst.png",
          speed: 10.0,
          life: 65,
          w: 56,
          h: 40,
          damage: 14,
          kbBase: 13,
          kbScale: 0.65,
          angle: 45,
          scale: 0.32,
        },
      }),
      sspecial: atk({
        name: "Investida Implacável",
        startup: 10,
        active: 22,
        recovery: 18,
        damage: 18,
        kbBase: 17,
        kbScale: 0.8,
        angle: 30,
        sprite: "charge",
        vx: 15.0,
        invuln: 12,
        hitbox: { x: 12, y: -72, w: 86, h: 58 },
      }),
      uspecial: atk({
        name: "Salto Titânico",
        startup: 7,
        active: 10,
        recovery: 20,
        damage: 13,
        kbBase: 14,
        kbScale: 0.5,
        angle: 86,
        sprite: "punch",
        vy: -16.0,
        vx: 2.0,
        invuln: 10,
        hitbox: { x: -12, y: -96, w: 56, h: 84 },
      }),
      dspecial: atk({
        name: "Rugido da Fera",
        startup: 12,
        active: 8,
        recovery: 24,
        damage: 15,
        kbBase: 15,
        kbScale: 0.7,
        angle: 70,
        sprite: "charge",
        hitbox: { x: -50, y: -35, w: 100, h: 42 },
      }),
      throw: atk({
        name: "Arremesso Sísmico",
        startup: 8,
        active: 3,
        recovery: 18,
        damage: 12,
        kbBase: 13,
        kbScale: 0.6,
        angle: 45,
      }),
      super: atk({
        name: "Cataclismo de Ferro",
        startup: 16,
        active: 24,
        recovery: 32,
        damage: 38,
        kbBase: 22,
        kbScale: 1.1,
        angle: 45,
        hitstun: 55,
        superMove: true,
        invuln: 28,
        sprite: "punch",
        hitbox: { x: -50, y: -85, w: 160, h: 95 },
      }),
    },
  },

  cavaleiro_tempestade: {
    id: "cavaleiro_tempestade",
    name: "Cavaleiro da Tempestade",
    title: "O Peão do Trovão",
    archetype: "Chefe / Relâmpago",
    color: "#52c7ff",
    portrait: "ui/portrait_evertinho.jpg",
    scale: 0.36,
    hurtW: 48,
    hurtH: 84,
    weight: 110,
    speed: 5.4,
    runSpeed: 8.2,
    accel: 0.7,
    friction: 0.76,
    airAccel: 0.42,
    airSpeed: 5.6,
    jump: 14.0,
    airJump: 12.8,
    gravity: 0.58,
    maxFall: 12.5,
    fastFall: 15.5,
    jumps: 2,
    anim: {
      idle: ["evertinho/idle_0.png", "evertinho/idle_1.png"],
      walk: ["evertinho/walk_0.png", "evertinho/walk_1.png"],
      run: ["evertinho/run.png"],
      jump: ["evertinho/jump.png"],
      punch: ["evertinho/punch.png"],
      special: ["evertinho/spin.png"],
      crouch: ["evertinho/throw.png"],
      hurt: ["evertinho/hurt.png"],
      win: ["evertinho/point.png"],
      down: ["evertinho/hurt.png"],
      charge: ["evertinho/mount.png"],
      throw: ["evertinho/throw.png"],
      point: ["evertinho/point.png"],
    },
    moves: {
      jab: atk({
        name: "Chicote Elétrico",
        startup: 4,
        active: 8,
        recovery: 9,
        damage: 6,
        kbBase: 6,
        kbScale: 0.25,
        angle: 65,
        hitstun: 14,
        isLasso: true,
        sprite: "special",
        hitbox: { x: -10, y: -78, w: 90, h: 80 },
      }),
      strong: atk({
        name: "Arremesso Tempestade",
        startup: 10,
        active: 3,
        recovery: 18,
        damage: 0,
        sprite: "punch",
        isLasso: true,
        projectile: {
          kind: "thunder_lasso",
          sprite: "evertinho/lasso_thunder.png",
          speed: 13.0,
          life: 55,
          w: 54,
          h: 34,
          damage: 15,
          kbBase: 13,
          kbScale: 0.7,
          angle: 35,
          scale: 0.25,
          isLasso: true,
        },
      }),
      nair: atk({
        name: "Vórtice de Raios",
        startup: 6,
        active: 8,
        recovery: 12,
        damage: 11,
        kbBase: 10,
        kbScale: 0.45,
        angle: 45,
        isLasso: true,
        sprite: "jump",
        hitbox: { x: 4, y: -72, w: 60, h: 60 },
      }),
      dair: atk({
        name: "Raio Descendente",
        startup: 9,
        active: 6,
        recovery: 15,
        damage: 12,
        kbBase: 9,
        kbScale: 0.6,
        angle: 270,
        isLasso: true,
        sprite: "throw",
        hitbox: { x: -8, y: -28, w: 50, h: 40 },
      }),
      uair: atk({
        name: "Trovão Ascendente",
        startup: 6,
        active: 6,
        recovery: 13,
        damage: 10.5,
        kbBase: 11,
        kbScale: 0.5,
        angle: 85,
        isLasso: true,
        sprite: "jump",
        hitbox: { x: -10, y: -102, w: 54, h: 46 },
      }),
      nspecial: atk({
        name: "Laço do Relâmpago Duplo",
        startup: 10,
        active: 3,
        recovery: 20,
        damage: 0,
        sprite: "special",
        isLasso: true,
        projectile: {
          kind: "thunder_lasso",
          sprite: "evertinho/lasso_thunder.png",
          speed: 13.5,
          life: 60,
          w: 54,
          h: 34,
          damage: 15,
          kbBase: 13,
          kbScale: 0.7,
          angle: 32,
          scale: 0.26,
          isLasso: true,
        },
      }),
      sspecial: atk({
        name: "Cavalo Elétrico",
        startup: 10,
        active: 4,
        recovery: 22,
        damage: 0,
        sprite: "point",
        assist: {
          kind: "horse",
          sprite: "evertinho/horse_thunder.png",
          speed: 15.0,
          life: 80,
          w: 85,
          h: 65,
          damage: 17,
          kbBase: 15,
          kbScale: 0.72,
          angle: 40,
          scale: 0.35,
          sound: "horse_whinny",
        },
      }),
      uspecial: atk({
        name: "Ascensão Elétrica",
        startup: 5,
        active: 12,
        recovery: 16,
        damage: 10,
        kbBase: 10,
        kbScale: 0.45,
        angle: 88,
        sprite: "mount",
        vy: -17.5,
        vx: 3.0,
        invuln: 10,
        hitbox: { x: -12, y: -98, w: 58, h: 90 },
      }),
      dspecial: atk({
        name: "Choque de Ferradura",
        startup: 11,
        active: 6,
        recovery: 22,
        damage: 14,
        kbBase: 13,
        kbScale: 0.65,
        angle: 65,
        sprite: "throw",
        hitbox: { x: -20, y: -70, w: 75, h: 60 },
      }),
      throw: atk({
        name: "Arremesso do Trovão",
        startup: 6,
        active: 3,
        recovery: 15,
        damage: 10,
        kbBase: 8,
        kbScale: 0.42,
        angle: 42,
        pull: true,
        isLasso: true,
        sprite: "throw",
        hitbox: { x: 16, y: -64, w: 90, h: 36 },
      }),
      super: atk({
        name: "Fúria da Tempestade",
        startup: 14,
        active: 24,
        recovery: 30,
        damage: 35,
        kbBase: 21,
        kbScale: 1.0,
        angle: 45,
        hitstun: 52,
        superMove: true,
        invuln: 25,
        sprite: "mount",
        vx: 16,
        hitbox: { x: -25, y: -92, w: 130, h: 90 },
      }),
    },
  },

  barao_ferradura: {
    id: "barao_ferradura",
    name: "Barão da Ferradura Negra",
    title: "O Ladrão da Aurora",
    archetype: "Chefe Final / Sombrio",
    color: "#b038ff",
    portrait: "ui/portrait_nox.jpg",
    scale: 0.36,
    hurtW: 48,
    hurtH: 84,
    weight: 120,
    speed: 5.2,
    runSpeed: 7.8,
    accel: 0.68,
    friction: 0.78,
    airAccel: 0.38,
    airSpeed: 5.2,
    jump: 13.5,
    airJump: 12.4,
    gravity: 0.6,
    maxFall: 12.8,
    fastFall: 15.8,
    jumps: 2,
    anim: {
      idle: ["nox/idle_0.png", "nox/idle_1.png"],
      walk: ["nox/walk.png"],
      run: ["nox/run.png"],
      jump: ["nox/jump.png"],
      punch: ["nox/punch.png"],
      special: ["nox/charge.png"],
      crouch: ["nox/charge.png"],
      hurt: ["nox/hurt.png"],
      win: ["nox/punch.png"],
      down: ["nox/hurt.png"],
    },
    moves: {
      jab: atk({
        name: "Golpe das Sombras",
        startup: 5,
        active: 4,
        recovery: 10,
        damage: 7,
        kbBase: 7,
        kbScale: 0.3,
        angle: 50,
        hitstun: 15,
        sprite: "punch",
        hitbox: { x: 18, y: -66, w: 52, h: 34 },
      }),
      strong: atk({
        name: "Ferradura Negra da Noite",
        startup: 11,
        active: 5,
        recovery: 18,
        damage: 16,
        kbBase: 16,
        kbScale: 0.85,
        angle: 35,
        hitstun: 25,
        hitlag: 12,
        sprite: "charge",
        hitbox: { x: 24, y: -70, w: 64, h: 44 },
      }),
      nair: atk({
        name: "Giro do Abismo",
        startup: 7,
        active: 8,
        recovery: 13,
        damage: 10.5,
        kbBase: 10,
        kbScale: 0.45,
        angle: 45,
        sprite: "jump",
        hitbox: { x: 6, y: -70, w: 54, h: 56 },
      }),
      dair: atk({
        name: "Pisão Sombrio",
        startup: 9,
        active: 6,
        recovery: 16,
        damage: 13,
        kbBase: 9,
        kbScale: 0.62,
        angle: 270,
        sprite: "charge",
        hitbox: { x: -10, y: -26, w: 48, h: 42 },
      }),
      uair: atk({
        name: "Garra Espectral",
        startup: 7,
        active: 6,
        recovery: 14,
        damage: 11,
        kbBase: 11,
        kbScale: 0.5,
        angle: 85,
        sprite: "jump",
        hitbox: { x: -8, y: -98, w: 50, h: 44 },
      }),
      nspecial: atk({
        name: "Laço de Sombras",
        startup: 11,
        active: 3,
        recovery: 20,
        damage: 0,
        sprite: "charge",
        isLasso: true,
        projectile: {
          kind: "dark_lasso",
          sprite: "cats/tom_orb.png",
          speed: 11.0,
          life: 65,
          w: 48,
          h: 48,
          damage: 14,
          kbBase: 12,
          kbScale: 0.6,
          angle: 35,
          scale: 0.38,
          isLasso: true,
          pull: true,
        },
      }),
      sspecial: atk({
        name: "Investida da Ferradura Negra",
        startup: 10,
        active: 18,
        recovery: 18,
        damage: 16,
        kbBase: 16,
        kbScale: 0.75,
        angle: 32,
        sprite: "charge",
        vx: 14.5,
        invuln: 8,
        hitbox: { x: 10, y: -70, w: 80, h: 56 },
      }),
      uspecial: atk({
        name: "Teletransporte Sombrio",
        startup: 5,
        active: 10,
        recovery: 16,
        damage: 10,
        kbBase: 10,
        kbScale: 0.42,
        angle: 88,
        sprite: "punch",
        vy: -16.5,
        vx: 2.2,
        invuln: 10,
        hitbox: { x: -12, y: -94, w: 54, h: 80 },
      }),
      dspecial: atk({
        name: "Vórtice do Vácuo",
        startup: 12,
        active: 6,
        recovery: 24,
        damage: 14,
        kbBase: 14,
        kbScale: 0.68,
        angle: 70,
        sprite: "charge",
        hitbox: { x: -45, y: -35, w: 90, h: 40 },
      }),
      throw: atk({
        name: "Puxão Sombrio",
        startup: 7,
        active: 3,
        recovery: 16,
        damage: 11,
        kbBase: 10,
        kbScale: 0.5,
        angle: 45,
        pull: true,
        isLasso: true,
      }),
      super: atk({
        name: "Eclipse da Ferradura Negra",
        startup: 16,
        active: 24,
        recovery: 32,
        damage: 36,
        kbBase: 22,
        kbScale: 1.05,
        angle: 45,
        hitstun: 55,
        superMove: true,
        invuln: 28,
        sprite: "charge",
        hitbox: { x: -45, y: -85, w: 150, h: 95 },
      }),
    },
  },
};

export const CHARACTER_IDS = ["evertinho", "fernanda", "nox"];
export const ALL_CHARACTER_IDS = ["evertinho", "fernanda", "nox", "touro_ferro", "cavaleiro_tempestade", "barao_ferradura"];
