function atk(partial) {
  return {
    startup: 6,
    active: 4,
    recovery: 12,
    damage: 6,
    kbBase: 8,
    kbScale: 0.42,
    angle: 45,
    hitstun: 14,
    hitlag: 6,
    shieldDamage: 4,
    sprite: "punch",
    hitbox: { x: 18, y: -62, w: 42, h: 30 },
    cancel: null,
    projectile: null,
    vx: 0,
    vy: 0,
    invuln: 0,
    name: "atk",
    ...partial,
  };
}

export const CHARACTERS = {
  fernanda: {
    id: "fernanda",
    name: "Fernanda",
    archetype: "Técnica",
    color: "#ff74b1",
    portrait: "ui/portrait_fernanda.png",
    scale: 0.32,
    hurtW: 40,
    hurtH: 78,
    weight: 86,
    speed: 5.4,
    runSpeed: 7.6,
    accel: 0.7,
    friction: 0.72,
    airAccel: 0.38,
    airSpeed: 5.2,
    jump: 13.6,
    airJump: 12.4,
    gravity: 0.52,
    maxFall: 11,
    fastFall: 14.5,
    jumps: 2,
    anim: {
      idle: ["fernanda/idle_0.png", "fernanda/idle_1.png"],
      walk: ["fernanda/walk_0.png", "fernanda/walk_1.png"],
      run: ["fernanda/run.png"],
      jump: ["fernanda/jump.png"],
      punch: ["fernanda/punch.png"],
      special: ["fernanda/special.png"],
      crouch: ["fernanda/crouch.png"],
      hurt: ["fernanda/hurt.png"],
      win: ["fernanda/win.png"],
      down: ["fernanda/down.png"],
    },
    moves: {
      jab: atk({
        name: "Soco",
        startup: 4,
        active: 3,
        recovery: 9,
        damage: 3.5,
        kbBase: 4,
        kbScale: 0.18,
        angle: 55,
        hitstun: 12,
        cancel: "jab2",
      }),
      jab2: atk({
        name: "Gatilho",
        startup: 5,
        active: 4,
        recovery: 14,
        damage: 4.5,
        kbBase: 7,
        kbScale: 0.28,
        angle: 48,
        hitstun: 13,
      }),
      strong: atk({
        name: "Cruzado",
        startup: 11,
        active: 5,
        recovery: 18,
        damage: 13,
        kbBase: 14,
        kbScale: 0.72,
        angle: 38,
        hitstun: 22,
        hitlag: 10,
        sprite: "punch",
        hitbox: { x: 22, y: -66, w: 50, h: 34 },
      }),
      nair: atk({
        name: "Aéreo",
        startup: 7,
        active: 8,
        recovery: 12,
        damage: 8,
        kbBase: 8,
        kbScale: 0.4,
        angle: 42,
        sprite: "jump",
        hitbox: { x: 8, y: -70, w: 46, h: 50 },
      }),
      dair: atk({
        name: "Aéreo baixo",
        startup: 10,
        active: 6,
        recovery: 16,
        damage: 9,
        kbBase: 6,
        kbScale: 0.5,
        angle: 270,
        sprite: "jump",
        hitbox: { x: -10, y: -28, w: 36, h: 36 },
      }),
      uair: atk({
        name: "Aéreo alto",
        startup: 7,
        active: 5,
        recovery: 14,
        damage: 8,
        kbBase: 9,
        kbScale: 0.45,
        angle: 82,
        sprite: "jump",
        hitbox: { x: -8, y: -96, w: 40, h: 36 },
      }),
      nspecial: atk({
        name: "Coração",
        startup: 12,
        active: 2,
        recovery: 22,
        damage: 0,
        sprite: "special",
        projectile: {
          kind: "heart",
          sprite: "fx/heart.png",
          speed: 9.5,
          life: 70,
          w: 36,
          h: 28,
          damage: 8,
          kbBase: 9,
          kbScale: 0.4,
          angle: 35,
          scale: 0.22,
        },
      }),
      sspecial: atk({
        name: "Didi",
        startup: 10,
        active: 3,
        recovery: 26,
        damage: 0,
        sprite: "run",
        projectile: {
          kind: "didi",
          sprite: "cats/didi_fire.png",
          speed: 11,
          life: 42,
          w: 48,
          h: 32,
          damage: 11,
          kbBase: 12,
          kbScale: 0.55,
          angle: 32,
          scale: 0.38,
        },
      }),
      uspecial: atk({
        name: "Tom — recuperação",
        startup: 6,
        active: 10,
        recovery: 18,
        damage: 7,
        kbBase: 8,
        kbScale: 0.38,
        angle: 88,
        sprite: "jump",
        vy: -15.5,
        vx: 2.2,
        invuln: 8,
        hitbox: { x: -16, y: -90, w: 48, h: 70 },
      }),
      dspecial: atk({
        name: "Tom — orbe",
        startup: 14,
        active: 2,
        recovery: 24,
        damage: 0,
        sprite: "crouch",
        projectile: {
          kind: "orb",
          sprite: "cats/tom_orb.png",
          speed: 7.2,
          life: 80,
          w: 34,
          h: 34,
          damage: 10,
          kbBase: 10,
          kbScale: 0.6,
          angle: 50,
          scale: 0.34,
        },
      }),
      throw: atk({
        name: "Arremesso",
        startup: 8,
        active: 2,
        recovery: 16,
        damage: 7,
        kbBase: 10,
        kbScale: 0.5,
        angle: 40,
      }),
    },
  },

  evertinho: {
    id: "evertinho",
    name: "Evertinho",
    archetype: "Peão",
    color: "#e8b84a",
    portrait: "ui/portrait_evertinho.png",
    scale: 0.34,
    hurtW: 46,
    hurtH: 82,
    weight: 104,
    speed: 4.6,
    runSpeed: 6.8,
    accel: 0.58,
    friction: 0.76,
    airAccel: 0.32,
    airSpeed: 4.6,
    jump: 13.0,
    airJump: 11.8,
    gravity: 0.58,
    maxFall: 12.2,
    fastFall: 15.2,
    jumps: 2,
    anim: {
      idle: ["evertinho/idle_0.png", "evertinho/idle_1.png"],
      walk: ["evertinho/walk_0.png", "evertinho/walk_1.png"],
      run: ["evertinho/run.png"],
      jump: ["evertinho/jump.png"],
      punch: ["evertinho/punch.png"],
      special: ["evertinho/spin.png"],
      crouch: ["evertinho/throw.png"],
      hurt: ["evertinho/hurt.png"],
      win: ["evertinho/point.png"],
      down: ["evertinho/hurt.png"],
      charge: ["evertinho/mount.png"],
      throw: ["evertinho/throw.png"],
      point: ["evertinho/point.png"],
    },
    moves: {
      jab: atk({
        name: "Laço giratório",
        startup: 5,
        active: 8,
        recovery: 10,
        damage: 4.5,
        kbBase: 5,
        kbScale: 0.2,
        angle: 70,
        hitstun: 13,
        cancel: "jab2",
        sprite: "special",
        hitbox: { x: -10, y: -78, w: 78, h: 78 },
      }),
      jab2: atk({
        name: "Laço puxão",
        startup: 6,
        active: 5,
        recovery: 14,
        damage: 6,
        kbBase: 4,
        kbScale: 0.22,
        angle: 40,
        pull: true,
        sprite: "throw",
        hitbox: { x: 18, y: -64, w: 70, h: 32 },
      }),
      strong: atk({
        name: "Laço arremesso",
        startup: 12,
        active: 3,
        recovery: 20,
        damage: 0,
        sprite: "punch",
        projectile: {
          kind: "lasso",
          sprite: "evertinho/lasso_loop.png",
          speed: 10,
          life: 42,
          w: 40,
          h: 28,
          damage: 11,
          kbBase: 10,
          kbScale: 0.5,
          angle: 32,
          scale: 0.22,
          pull: true,
        },
      }),
      nair: atk({
        name: "Aéreo",
        startup: 8,
        active: 7,
        recovery: 14,
        damage: 9,
        kbBase: 9,
        kbScale: 0.42,
        angle: 40,
        sprite: "jump",
        hitbox: { x: 6, y: -72, w: 50, h: 54 },
      }),
      dair: atk({
        name: "Laço baixo",
        startup: 11,
        active: 6,
        recovery: 16,
        damage: 10,
        kbBase: 7,
        kbScale: 0.5,
        angle: 270,
        sprite: "throw",
        hitbox: { x: -8, y: -28, w: 44, h: 36 },
      }),
      uair: atk({
        name: "Laço alto",
        startup: 8,
        active: 6,
        recovery: 15,
        damage: 9,
        kbBase: 10,
        kbScale: 0.45,
        angle: 82,
        sprite: "jump",
        hitbox: { x: -10, y: -100, w: 48, h: 42 },
      }),
      nspecial: atk({
        name: "Laço mágico",
        startup: 14,
        active: 3,
        recovery: 24,
        damage: 0,
        sprite: "special",
        projectile: {
          kind: "magic",
          sprite: "evertinho/lasso_magic.png",
          speed: 8.5,
          life: 70,
          w: 42,
          h: 32,
          damage: 13,
          kbBase: 12,
          kbScale: 0.58,
          angle: 28,
          scale: 0.2,
        },
      }),
      sspecial: atk({
        name: "Ataque montado",
        startup: 10,
        active: 16,
        recovery: 18,
        damage: 14,
        kbBase: 14,
        kbScale: 0.62,
        angle: 30,
        sprite: "charge",
        vx: 12.5,
        hitbox: { x: 8, y: -70, w: 72, h: 56 },
      }),
      uspecial: atk({
        name: "Invocar cavalo",
        startup: 7,
        active: 12,
        recovery: 18,
        damage: 8,
        kbBase: 9,
        kbScale: 0.4,
        angle: 86,
        sprite: "point",
        vy: -16.4,
        vx: 2.4,
        invuln: 8,
        hitbox: { x: -12, y: -96, w: 52, h: 86 },
      }),
      dspecial: atk({
        name: "Laço do trovão",
        startup: 13,
        active: 3,
        recovery: 26,
        damage: 0,
        sprite: "throw",
        projectile: {
          kind: "thunder",
          sprite: "evertinho/lasso_thunder.png",
          speed: 11.5,
          life: 50,
          w: 48,
          h: 30,
          damage: 12,
          kbBase: 11,
          kbScale: 0.65,
          angle: 40,
          scale: 0.22,
        },
      }),
      throw: atk({
        name: "Laço pegada",
        startup: 8,
        active: 3,
        recovery: 16,
        damage: 8,
        kbBase: 6,
        kbScale: 0.35,
        angle: 42,
        pull: true,
        sprite: "throw",
        hitbox: { x: 16, y: -64, w: 86, h: 36 },
      }),
    },
  },
};

export const CHARACTER_IDS = Object.keys(CHARACTERS);
